### ISSUE TITLE
blank images in `demo/class/bindata/predictions`

### ISSUE THREAD

**Issue by brisker** [pkainz/MICCAI2015#2] opened 2016-08-27 06:25 UTC
right now after I run the "/home/sjtu/code/MICCAI2015-code-master/demo/class/run.sh" I found that in the "/home/sjtu/code/MICCAI2015-code-master/demo/class/bindata/predictions" there are just three blank image like this: 
![image](https://cloud.githubusercontent.com/assets/13804492/18025637/445cc808-6c62-11e6-97a0-e2862d78e0d7.png)

and the  in the command window it reads like this:
Analyzing image ./bindata/predictions/BM_GRAZ_HE_0008_01.png (66.6667%)
=== INDIVIDUAL IMAGE STATISTICS ===

image_conf_mtrx =

```
     364     1439636
       0           0
```

Total detections: 1440000, total valid ground truth: 364
Ground truth out of bounds: 0 (0.000000%)
Image accuracy: 0.000253, distance error mean (SD): 9.998339 (0.015778)
Recall: 1.000000, Precision: 0.000253, F1: 0.000505

1.Have I got something wrong? Is it that when the optimazation is done, the three blank images will turn into  the cell detection result images?
2. What is the difference between "class" folder files and "regr"  folder files? Run the "run.sh"  in the two different folders will generate different results?

**Comment by pkainz** [comment] 2016-08-27 07:49
The `class` method implements a binary Random Forest classifier that predicts, for each pixel, the probability of being a cell center. The `regr` method is the proximity score regression. 

The three images should not be white. It seems that the classifier predicts a cell center for each pixel, which is weird. What's your system config?

**Comment by brisker** [comment] 2016-08-27 07:51
@pkainz   Ubuntu14.04, Matlab 2015a Did you mean this environment?

**Comment by pkainz** [comment] 2016-08-27 07:52
@brisker Yes, and I also mean the versions of the Random Forest dependencies.

**Comment by brisker** [comment] 2016-08-27 08:07
@pkainz    Opencv3.0.0 ，libblitz 0.0.0,  libconfig++ 9.1.3, libboost1.55.0, cmake 2.8, gcc 4.8

**Comment by pkainz** [comment] 2016-08-27 08:31
@brisker Looks good, does the code compile without problems? I haven't tested with OpenCV 3 yet, I used OpenCV 2.4.8 and 2.4.9. Can you attach `class/bindata/trees/tree_0.txt` here?

**Comment by brisker** [comment] 2016-08-27 08:38
@pkainz   I just compile it again(class) and it reads like this:
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
Linking CXX executable icgrf-celldet-class
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Built target icgrf-celldet-class
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)

I think there is no problem in compilaton. But I do not quite understand what do you mean "attach class/bindata/trees/tree_0.txt"?

**Comment by brisker** [comment] 2016-08-27 08:38
@pkainz   I just compile it again(class) and it reads like this:
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
Linking CXX executable icgrf-celldet-class
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Built target icgrf-celldet-class
/usr/bin/cmake: /home/sjtu/anaconda2/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)


I think there is no problem in compilaton. But I do not quite understand what do you mean "attach class/bindata/trees/tree_0.txt"?

**Comment by pkainz** [comment] 2016-08-27 08:44
@brisker A sibling directory of `predictions` (you showed me in your screenshot) should be `trees`. Attach the file `tree_0.txt` to your next post in this forum so that I can examine the structure of one of the trees.

**Comment by brisker** [comment] 2016-08-27 08:47
[tree_0.txt](https://github.com/pkainz/MICCAI2015/files/440563/tree_0.txt)
@pkainz

**Comment by pkainz** [comment] 2016-08-27 08:57
The tree looks reasonable, so training works properly. There must be some issue when writing out the images. Can you try with OpenCV 2.4.9?

**Comment by brisker** [comment] 2016-08-28 06:43
@pkainz   If I need to reinstall opencv, can you give some advice to avoid possible problems? just download opencv2.4.9 and install? Or do something in advance?

**Comment by brisker** [comment] 2016-08-28 09:57
@pkainz  after try with opencv2.4.9, the images looks like this:
![image](https://cloud.githubusercontent.com/assets/13804492/18032928/91b4058a-6d48-11e6-8492-dff92393275c.png)
but why the recall, precision all 0 or NaN? and the all_results.mat for class method looks like this:
![image](https://cloud.githubusercontent.com/assets/13804492/18033682/ecde0428-6d5d-11e6-82bb-67ad62df5c42.png)

I attached a log.txt and could you please take a look?(after run the run.sh in the class folder)
[log.txt](https://github.com/pkainz/MICCAI2015/files/441066/log.txt)

Besides, when I run the run.sh in the regr folder, the same problem occurs. The all_results.mat for regr method looks like this:
![image](https://cloud.githubusercontent.com/assets/13804492/18033890/734cc0be-6d61-11e6-8fd5-3bfb9775118b.png)

**Comment by brisker** [comment] 2016-08-28 11:51
@pkainz   Besides, I have run the run.sh in the regr folder, it seemed that the training process is really slow. So is it naturally a lot slower than the "class" method?

**Comment by brisker** [comment] 2016-08-29 12:47
@pkainz

**Comment by pkainz** [comment] 2016-08-30 18:08
@brisker These values you mentioned are for a confidence (class) or score (regr) threshold of 255 (in the 8bit range). The important values are the ones with the prefix `best_*`, which are non-zero and non-NaN's in your case. 
The way these post-processing (evaluation) scripts work is as follows: 
1. smooth with a Gaussian
2. remove low scores/confidences using a threshold (which we also vary in the 8-bit grey value range, i.e. at each possible grey value, to determine the precision-recall curves)
3. perform non-maximum suppression to determine local maxima

Therefore you get a `perf_data` matrix, where - for each threshold - the performance measures are recorded. Btw,  you should also see a file `best_results.txt` in your results folder, which holds the best threshold and the corresponding performance values. 

For the other problem with the white images, I will have to update the code for OpenCV >= 3.0.0 compatibility.

**Comment by brisker** [comment] 2016-08-30 18:17
i attach a log.txt and could you please take a look？ the reason I attached it is that i found something wrong but i can not figure out where is wrong. 

发自我的 iPhone

**Comment by pkainz** [comment] 2016-08-30 18:24
@brisker sorry, can't view the attachment...

**Comment by brisker** [comment] 2016-08-30 18:29
@pkainz   i got error when running run.sh and i can not save the figures， the error is in the log.txt I have attached in my previous message…

**Comment by brisker** [comment] 2016-08-30 18:32
@pkainz  the log.txt is attached in the message 2  days ago

**Comment by pkainz** [comment] 2016-08-30 18:41
@brisker Nothing's wrong, there are simply no peaks in the prediction map above the threshold of 249. Therefore, you don't find any true positives, or false positives. Hence, you miss all ground truth cells and according to the definitions of the metrics you end up with precision being `NaN` (division by zero) and recall being zero. 
Check the log for a threshold around 150. I ignored all these values, since they don't contribute anything to the performance, but were just in the evaluated range. If you want to dig deeper, examine the `computeDetectionPerformance` function.

**Comment by pkainz** [comment] 2016-08-30 19:42
@brisker Regarding the error in the log: the `savefig` API seems to have changed in [Matlab >2013b](http://de.mathworks.com/help/matlab/ref/savefig.html). Check the documentation for a substitute and replace the call in the `evaluate.m` script.

**Comment by brisker** [comment] 2016-08-31 11:51
@pkainz    The bug reads like this:
error using savefig (line 128)
No file name specified.

error saveasfig (line 6)
savefig(h, name);

error saveas (line 140)
    feval( ['saveas' format], h, name )

error evaluate (line 284)
        saveas(prPlot, strcat(path_figures, method_str_short, '_pr-curve'),
        'fig');

error run (line 96)
evalin('caller', [script ';']);


and I do not quite understand you by saying "replace the call in evaluate.m" since  the bug line in evaluate.m reads like this:
 saveas(prPlot, strcat(path_figures, method_str_short, '_pr-curve'), 'fig');
Did you mean replace saveas?

**Comment by pkainz** [comment] 2016-08-31 11:58
@brisker Yes, either adapt this line to work with your Matlab version and you will be fine having figures, or otherwise turn off the plotting of this figure, e.g. [see here](https://github.com/pkainz/MICCAI2015/blob/master/demo/class/evaluate.m#L26) for the `class` method. If none of this works, just comment these lines and check again.

**Comment by brisker** [comment] 2016-08-31 12:17
@pkainz   The problem is the savefig.m has the same name with the MICCAI2015-code-master/code/toolbox/external/other/savefig.m , I rename it, and it went well.

**Comment by pkainz** [comment] 2016-08-31 12:19
@brisker Alright, I'll close this issue then.

**Closed as completed by pkainz** 2016-08-31 12:19 UTC
Labels: bug, question
